Initial docker setup
mrdjohnson/llm-x pull request #19
Opened 2024-05-06 13:28 UTC by VickTor61

2024-05-06 14:21 UTC, VickTor61 commented on .dockerignore
> +**/.DS_Store
Yeah these were created when i intialised docker. Let me clean it up

2024-05-07 00:56 UTC, mrdjohnson requested changes
docker compose part does not seem to be working?

2024-05-07 00:56 UTC, mrdjohnson commented on Dockerfile
> +COPY package.json yarn.lock ./
we already copied the entire project, do we still need this as well?

2024-05-07 00:56 UTC, mrdjohnson commented on Dockerfile
> +RUN yarn install --frozen-lockfile
not important: I ran `docker build` with this flag: `--progress=plain` to see the logs, it showed this:

```
 The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
```

maybe we can use immutable instead?

2024-05-07 00:56 UTC, mrdjohnson commented on Dockerfile
> +CMD ["yarn", "preview", "--host", "--port", "5173"]
👏  nice

2024-05-07 00:56 UTC, mrdjohnson commented on compose.yaml
> +      target: final
what command are you running to get docker compose to work? 

`docker compose up` says it cannot find target final

2024-05-07 15:10 UTC, VickTor61 commented
> docker compose part does not seem to be working?

Yeah i mentioned i just added the boiler plate. Needed to know if we needed it at the moment

2024-05-07 15:11 UTC, VickTor61 commented on Dockerfile
> +RUN yarn install --frozen-lockfile
I didn't know it was deprecated. Didn't see any warnings on my end but will update that.

2024-05-07 18:28 UTC, VickTor61 commented on Dockerfile
> +COPY package.json yarn.lock ./
Naa. another oversight on my end. Already fixed that. Pushing now

2024-05-08 08:58 UTC, merged